### ISSUE TITLE
Protected JWS::isExpired

### ISSUE THREAD

**Issue by TomAdam** [namshi/jose#32]
I'm using JOSE for handling JWTs in an API client. I would like to be able to check if the token is valid in terms of expiry without running a JWS::isValid. It would be nice if the JWS::isExpired was public. Happy to make a PR if there is a chance of it getting accepted.

**Comment by odino** [comment]
hey @TomAdam :)

what is the scenario for this change? We discussed it way back in the day and decided to keep it private so that people wouldnt mess around and get confused. Though, if you have a valid scenario we should review it!

**Comment by TomAdam** [comment]
I am building an API client for a JWT authenticated API. I have used JOSE in a Guzzle plugin pretty much only to manage expiry - I'm not checking validity in any other way. Obviously I could have done this without JOSE, but I didn't want to reimplement the token unpacking. We use JOSE the server end of the API too, so I also wanted to keep the library common between the two.

At the moment JOSE can be used client side, but managing token expiry has to be done externally to the library. It just feels a bit wrong copying the isExpired method out of the lib and into the Guzzle plugin. In my mind isExpired should be public as it generally isn't possible for a client to validate a token, but it is beneficial for them to know if the token has expired and they need a new one.

I have created a gist: https://gist.github.com/TomAdam/6f2ddb987a18fb5692f8

Please don't be too judgemental on the quality of this plugin - it is for our internal use and I couldn't afford the time to refactor it.

Expiry check is line 80, and a replacement token is fetched line 86 if required. I hope this explains the use case effectively. Happy to answer any more questions.

**Comment by odino** [comment]
Why would I be judgemental man? Production code is always much different than ideal code, and in 2009 I was writing [code like this](http://www.slideshare.net/odino/lets-rock/52) :)

So dont worry :) you're always welcome. As far as your use case is concerned I think it's fair to say that it is a rreal-world use case -- but one thing I want to ask you is: say that the validation on your side works (because the client is in GMT+8) but then fails on the server (GMT+12) and then token unfortunately expires in between the timezone :) then shouldn't you also always implement a logic that re-authenticates the client if the server tells him that he's unauthorized?

ie. we regenerate tokens in this way in our internal apps, or cache them for very limited time

Let me know what you think -- if you feel string about having the expiration checked on the client I think we can make it public without problems :)

**Comment by TomAdam** [comment]
Thanks, I'm still hoping to find the time to clean this up and release the plugin against the current version of Guzzle.

Date issues are a good point. It didn't occur to me as our client is in the same timezone as the API. You made me realise I had no idea how dates were specced in JWT, so I checked the docs:

> NumericDate
> A JSON numeric value representing the number of seconds from 1970-01-01T00:00:00Z UTC until the specified UTC date/time, ignoring leap seconds.
>
> 4.1.4.  "exp" (Expiration Time) Claim
>
>The "exp" (expiration time) claim identifies the expiration time on or after which the JWT MUST NOT be accepted for processing.  The processing of the "exp" claim requires that the current date/time MUST be before the expiration date/time listed in the "exp" claim. Implementers MAY provide for some small leeway, usually no more than a few minutes, to account for clock skew.  Its value MUST be a number containing a NumericDate value.  Use of this claim is OPTIONAL.

Do you think this is still an issue with the time based on UTC? This should make it timezone insensitive shouldn't it? I find dates a bit tricky to work with at times, but I think a ```->format('U')``` should give the same output regardless of timezone.

There is actually a re-authentication procedure starting line 53 - it catches unauthorised responses and attempts to re-authenticate, however it does not force a new token. In this case if skew caused the token to appear unexpired client side but expired server side there could be a problem. Perhaps I should be forcing a new token on a 401.

I think that the visibility of isExpired should depend on whether you consider the JOSE library for use client side. If so it could also be a benefit to allow access to the raw string token, so that it doesn't have to be rebuilt for use in headers. To be honest I'm not really sure I'm using the lib in the way you intended.

**Comment by odino** [comment]
I think it's fine, we can make it public :)

regarding the timezone issue, always remember that you dont 100% end up evaluating tokens on safe, server-side environments. For example, if your client is a javascript one, the timezone validation will rely on the system / browser date, which can be manipulated by the user. So yeah it's a tricky matter, though in your own PHP implementation you have more control over it. But at the end of the day I would recommend relying on re-authentication rather than validating the token on the client

**Comment by TomAdam** [comment]
Wow, had totally missed this one. Change no longer required as method has been pulled out into SimpleJWS - a great decision IMO.

**Comment by odino** [comment]
:+1:

**Comment by kbond** [comment]
Could you make it public in `SimpleJWS`?

**Comment by odino** [comment]
hey @kbond, feel free to open a PR and we'll get it merged :)
